apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.name }}-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb.rootPassword | b64enc | quote }}
