apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.server.name }}-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  doppler-token: {{ .Values.server.doppler.token | quote }}
