apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.server.name }}-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.server.doppler.enabled }}
  doppler-token: {{ .Values.server.doppler.token | quote }}
  {{- else }}
  db-url: "mongodb://{{ .Values.mongodb.rootUsername }}:{{ .Values.mongodb.rootPassword }}@{{ .Values.mongodb.name }}:27017/{{ .Values.mongodb.database }}?authSource=admin&retryWrites=true&w=majority"
  {{- end }}
