replicaCount: 1

image:
  repository: ghcr.io/berryhill/ccxt-bot-server
  pullPolicy: Always
  tag: "0.0.4"

imagePullSecrets:
  - name: ghcr-secret

# Doppler configuration
dopplerToken: ""
environment: "dev"

# API Configuration
apiUrl: "http://ccxt-bot-server:80"  # Internal K8s service URL

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-http"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: dev.api.ccxt.berryhill.dev
      paths:
        - path: /
          pathType: Prefix
    - host: dev.api.ccxt.berryhill.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ccxt-bot-server-tls
      hosts:
        - dev.api.ccxt.berryhill.dev

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - ccxt-bot-server
        topologyKey: topology.kubernetes.io/zone
